services:
  mariadb:
    container_name: mariadb
    networks:
      - mynetwork
    build:
      context: requirements/mariadb
      dockerfile: dockerfile
    image: mariadb:img
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
    restart: on-failure
  nginx:
    container_name: nginx
    networks:
      - mynetwork
    depends_on:
      - wordpress
    build:
      context: requirements/nginx
      dockerfile: dockerfile
    image: nginx:img
    volumes:
      - wordpress:/var/www/html
    env_file: .env
    ports:
      - "443:443"
    restart: on-failure

  wordpress:
    container_name: wordpress
    networks:
      - mynetwork
    build:
      context: requirements/wordpress
      dockerfile: dockerfile
    image: wordpress:img
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy
    restart: on-failure
    expose:
      - "9000"

volumes:
  wordpress:
    driver: local
    driver_opts:
      type : 'none'
      o: 'bind'
      device: '/home/kzerri/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
       type : 'none'
       o: 'bind'
       device: '/home/kzerri/data/mariadb'
networks:
  mynetwork:
    driver: bridge