FROM debian:bullseye

RUN apt-get update -y && apt-get install mariadb-server -y && apt-get install mariadb-client -y

COPY ./tools/config.cnf /etc/mysql/mariadb.conf.d/

RUN mkdir /scripts

COPY ./tools/script.sh /scripts/

RUN chmod +x  scripts/script.sh

EXPOSE 3306

CMD ["scripts/script.sh"]
