FROM debian:bullseye

RUN apt-get update -y && apt-get install wget -y\
    php7.4\
    php-fpm\
    php-mysql\
    mariadb-client

COPY tools/script.sh /

RUN mkdir -p /run/php

CMD [ "bash", "./script.sh" ]
