FROM debian:bullseye

RUN apt-get update -y && apt-get install nginx -y && apt-get install openssl -y

RUN mkdir -p /etc/nginx/ssl

RUN openssl req -x509 -nodes -out /etc/nginx/ssl/inception.cer -keyout /etc/nginx/ssl/inception.key -subj "/C=MR/ST=KH/L=Khouribga/O=42/OU=student/CN=kzerri.42.fr/UID=kzerri"

COPY conf/nginx.conf /etc/nginx/nginx.conf

CMD [ "nginx", "-g", "daemon off;"]
