FROM debian:bullseye

RUN apt-get update -y && apt-get install nginx -y && apt-get install openssl -y

RUN mkdir -p /etc/nginx/ssl

RUN cd /etc/nginx/ssl

RUN openssl req -x509 -nodes -out inception.cer -keyout inception.key -subj "/C=MR/ST=KH/L=Khouribga/O=42/OU=student/CN=kerri.42.fr/UID=kzerri"

COPY conf/nginx.conf /etc/nginx/nginx.conf

RUN chmod 755 /var/www/html

RUN chown -R www-data:www-data /var/www/html

CMD [ "nginx", "-g", "daemon of;"]